### PR TITLE
Fix exports to work with cabal HEAD

### PR DESCRIPTION
**Pull request by hasufell**
@Mikolaj

### CODE REVIEW

**Comment by Mikolaj** [comment]
Great job. I'm not sure what severity of warnings we are going to issue in 3.8 for such imperative conditionals as in the original, but certainly it's going to be frowned upon. :)

**Comment by Mikolaj** [comment]
BTW, the PR just landed: https://github.com/haskell/cabal/pull/7966, so now it would be an excusable warning. After your fix, the warning is, I hope, gone.

**Comment by mightybyte** [comment]
Let's wait until these changes land in an officially released cabal before we merge this.

**Comment by hasufell** [comment]
> Let's wait until these changes land in an officially released cabal before we merge this.

Why? This works with any cabal version.

**Pull request closed without merging**
